apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions-account
  namespace: lennart
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-actions-role
  namespace: lennart
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - pods/exec
      - configmaps
      - serviceaccounts
      - services
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - networking.k8s.io # Add this block for ingresses
    resources:
      - ingresses
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions-rolebinding
  namespace: lennart
subjects:
  - kind: ServiceAccount
    name: github-actions-account
    namespace: lennart
roleRef:
  kind: Role
  name: github-actions-role
  apiGroup: rbac.authorization.k8s.io
