name: Build and Push Docker Image

on:
  workflow_call:

jobs:
  build-image:
    runs-on: ubuntu-22.04
    name: build & push docker image
    steps:
      - uses: actions/checkout@v4
        name: checkout backend
      - run: |
          ls
        name: debug
      - name: set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: lnart/dryager-backend
          tags: |
            type=raw,value=${{ github.sha }}
            type=raw,value=latest
      - name: log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
