name: Staging Deployment Backend

on:
  pull_request:
    branches:
      - blue
  push:
    branches:
      - blue

jobs:
  integrate:
    uses: ./.github/workflows/integrate.yml@master

  build-image:
    needs: integrate
    uses: ./.github/workflows/build-and-push-docker.yml@master
    secrets: inherit

  push-staging:
    needs: [integrate, build-image]
    uses: ./.github/workflows/deploy-image.yml@master
    with:
      deployment: kubernetes/blueDeployment.yml
      service: kubernetes/blueService.yml
      ingress: kubernetes/ingress.yml
    secrets: inherit
