# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Backend CI

on:
  push:

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 21
      - run: npm ci
      - run: npm run format -- --check
      - run: npm run test
      - run: npm run build
  test-build:
    name: build to check compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout backend
        with:
          sparse-checkout: |
            
      - uses: actions/setup-node@v3
        name: Setup Node.js
        with:
          node-version: "21.1.0"
      - run: npm ci
        name: Install dependecies
      - run: npm run build
        name: build the project with npm



