name: Staging Deployment Backend

on:
  push:
    branches:
      - master

jobs:
  integrate:
    uses: ./.github/workflows/integrate.yml

  build-image:
    needs: integrate
    uses: ./.github/workflows/build-and-push-docker.yml
    secrets: inherit

  push-staging:
    needs: [integrate, build-image]
    uses: ./.github/workflows/deploy-image.yml
    secrets: inherit
