name: Staging Deployment Backend

on:
  push:
    branches:
      - master

jobs:
  integrate:
    uses: ./github/workflows/integrate.yml

  build-image:
    needs: integrate
    uses: ./github/worflows/build-and-push-docker.yml

  push-staging:
    runs-on: ubuntu-22.04
    name: deploy changes on staging
    needs: build-image
    steps:
      - name: set the kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBE_SERVER_URL }}
          k8s-secret: ${{ secrets.KUBE_SERVICE_ACC_SECRET }}
          new-tag: ${{github.sha}}
      - uses: actions/checkout@v4
        name: checkout deployments
        with:
          submodules: "recursive"

      - name: deploy to the kubernetes cluster
        uses: azure/k8s-deploy@v4
        with:
          action: deploy
          force: true
          strategy: basic
          namespace: lennart
          manifests: |
            kubernetes/blueDeployment.yml
            kubernetes/blueService.yml
            kubernetes/ingress.yml
          images: |
            lnart/dryager-backend:${{ github.sha }}
